### ISSUE TITLE
Where da robot at? 

### ISSUE THREAD

**Issue by samayo** [zexiplus/WALL.E#1]
Where is the Robot? 

Do you have any demo pages? I tried to install the repo as per the readme and I got this error:

```
npm ERR! notsup Unsupported platform for raspi-io@8.1.0: wanted {"os":"any","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    any
npm ERR! notsup Valid Arch:  arm
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

**Comment by zexiplus** [comment]
ok  if you install on pc ,that error will happen
you can avoid the error by delete the dependencies("raspi-io": "^8.0.1", "johnny-five": "^0.11.7") in package.json ,then run npm install,that error won't happen again

if you run it in pc,you can only see the webfont pages,not all 
if you want to run it all ,you should have a raspiberry-pi and install on it  
en....the project is unfinished,if you want to see some pages you can visit https://jsrobot.herokuapp.com/

**Comment by samayo** [comment]
thanks
